services:
  evrinoma.fcr.constraint.property.id:
    class: Evrinoma\FcrBundle\Constraint\Property\Id

  evrinoma.fcr.constraint.property.description:
    class: Evrinoma\FcrBundle\Constraint\Property\Description

  evrinoma.fcr.constraint.property.active:
    class: Evrinoma\FcrBundle\Constraint\Property\Active
